-- Add new columns for exact Excel matching
ALTER TABLE sites 
ADD COLUMN IF NOT EXISTS is_metro BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS qty INTEGER DEFAULT 1,
ADD COLUMN IF NOT EXISTS total_sq_ft NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS printable_size TEXT,
ADD COLUMN IF NOT EXISTS metro_line TEXT,
ADD COLUMN IF NOT EXISTS metro_pillars TEXT,
ADD COLUMN IF NOT EXISTS no_of_pillars INTEGER,
ADD COLUMN IF NOT EXISTS no_of_displays INTEGER;
